mini_cheetah:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  servo_0_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: fl_abad_to_body
    pid: {p: $(arg P), i: $(arg I), d: $(arg D)}
